version: '3'

networks:
    docdb:

services:

    mongodb:
        image: mongo:4.4
        restart: always
        container_name: mongodb
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        networks:
            - docdb

    cadvisor:
        container_name: cadvisor
        image: gcr.io/cadvisor/cadvisor:v0.40.0
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:ro
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
            # - /dev/disk/:/dev/disk:ro
        privileged: true
        devices:
          - "/dev/kmsg:/dev/kmsg"
        ports:
            - 7000:7000
            - 8080:8080
        networks:
            - docdb
        
    exporter-docdb:
        build:
            network: host
            context: .
            dockerfile: Dockerfile
        container_name: exporter-docdb
        environment: 
            PORT: 5000
            DOCDB_HOST: mongodb
            DOCDB_PASSWORD: example
            DOCDB_TLS: 0
        ports:
            - 5000:5000
        depends_on:
            - mongodb
        networks:
            - docdb

        
    prometheus:
        image: prom/prometheus:v2.30.0
        container_name: prometheus
        restart: always
        volumes:
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--web.console.libraries=/etc/prometheus/console_libraries'
            - '--web.console.templates=/etc/prometheus/consoles'
            - '--web.enable-lifecycle'
        expose:
            - 9090
        ports:
            - 9090:9090
        depends_on:
            - exporter-docdb
        networks:
            - docdb


    grafana:
        image: grafana/grafana:8.1.5
        container_name: grafana
        # environment:
        #     GF_PATHS_PROVISIONING: /etc/conf/provisioning
        volumes: 
        - ./grafana/grafana.ini:/usr/share/grafana/conf/defaults.ini
        # - ./data:/var/lib/grafana/db:rw
        - ./grafana/provisioning:/etc/grafana/provisioning:rw
        ports:
            - "3000:3000"
        networks:
            - docdb
        depends_on:
            - prometheus