apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    # <int> org id. will default to orgId 1 if not specified
    orgId: 1
    # <string> url
    url: http://prometheus:9090
